version: "3"

services:

    webcrawler:
        container_name: web_crawler_service
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile.ai_service
        networks:
            - apinetwork
        expose:
            - "8000"
        ports:
            - "8002:8000"


networks:
    apinetwork:
